enum class MAV_TYPE {
    // copter
    MAV_TYPE_HELICOPTER,
    MAV_TYPE_TRICOPTER,
    MAV_TYPE_QUADROTOR,
    MAV_TYPE_HEXAROTOR,
    MAV_TYPE_OCTOROTOR,
    MAV_TYPE_DECAROTOR,
    MAV_TYPE_DODECAROTOR,
    MAV_TYPE_COAXIAL,

    // plane
    MAV_TYPE_FIXED_WING,

    // rover
    MAV_TYPE_GROUND_ROVER,
    // boat
    MAV_TYPE_SURFACE_BOAT,
    // tracker
    MAV_TYPE_ANTENNA_TRACKER,
    // sub
    MAV_TYPE_SUBMARINE,
}